version: "3"

services:
  frontend:
    build: "frontend/"
    ports:
      - "3000:3000"
  backend:
    build: "backend/"
    environment:
      PORT: "3001"
      OMDBAPIKEY: "<INSERT YOUR OMDB API KEY HERE!>"
    ports:
      - "3001:3001"
